version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pulsebet-postgres
    environment:
      POSTGRES_USER: pulsebet
      POSTGRES_PASSWORD: pulsebet
      POSTGRES_DB: pulsebet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
