version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pulsebet-postgres
    environment:
      POSTGRES_USER: pulsebet
      POSTGRES_PASSWORD: pulsebet
      POSTGRES_DB: pulsebet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.5
    container_name: pulsebet-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644" # admin UI / metrics, mo≈æe i bez ovoga
volumes:
  pgdata:
