serviceName: "betservice"
httpPort: 8082

kafka:
  brokers:
    - "redpanda:9092"
  groupId: "betservice-group"
  topics:
    matchCreated: "match_created"
database:
  host: "postgres"
  port: 5432
  user: "pulsebet"
  password: "pulsebet"
  name: "betservice_db"