serviceName: "gameservice"
httpPort: 8081

kafka:
  brokers:
    - "localhost:19092"
  groupId: "gameservice-group"
  topics:
    matchCreated: "match_created"
database:
  host: "0.0.0.0"
  port: 5432
  user: "pulseapp"
  password: "pulseapp"
  name: "pulsebet"