serviceName: "gameservice"
httpPort: 8081

kafka:
  brokers:
    - "redpanda:9092"
  groupId: "gameservice-group"
  topics:
    matchCreated: "match_created"
database:
  host: "postgres"
  port: 5432
  user: "pulsebet"
  password: "pulsebet"
  name: "gameservice_db"